languageCode = "en-us"
title = "Edward’s Brain Dump"
baseURL = "http://localhost:1313/cupper/"
canonifyURLs = true
theme = "cupper"
publishDir = "docs"

[params]
  description = "Edward’s Brain Dump: AI, Code, and Mild Panic"