languageCode = "en-us"
title = "Edward’s Brain Dump"
baseURL = "https://zw4315.github.io/"
canonifyURLs = true
theme = "cupper"
publishDir = "docs"

[params]
  description = "Edward’s Brain Dump: AI, Code, and Mild Panic"