name: Deploy Hugo site to GitHub Pages

on:
  push:
    branches:
      - master  # 当 `cupper.git` 的 main 分支有更新时触发

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout cupper.git repository
        uses: actions/checkout@v4

      - name: Install Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'

      - name: Build Hugo site
        run: hugo --minify  # Hugo 生成静态站点到 `docs/`

      - name: Deploy to GitHub Pages repository
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs  # 这里是 Hugo 生成的静态网站目录
          external_repository: zw4315/zw4315.github.io  # 目标 GitHub Pages 仓库
          publish_branch: master  # 把 `docs/` 里的内容推送到 `zw4315.github.io.git`
